### ISSUE TITLE
Map doesn't respond to Geo

### ISSUE THREAD

**Issue by mushon** [mushon/ST-sea_change#2]
Map doesn't move despite the fact that the geo points were set

**Comment by akariv** [comment]
The problem lies in the fact that you didn't use the AirTable template but tried to make changes to the existing one... there were many columns missing and many with wrong names.

**Comment by akariv** [comment]
I changed CONFIGURATION.ts to point to this airtable:

https://airtable.com/appp3Khl8aGLWR2xx/tblgK83aAbeUShSvb/viwWjnA4iUYlaPABx?blocks=hide

there's some content in the Settings area that needs to be fixed, other than  that looks fine.

**Comment by mushon** [comment]
Thanks and sorry for messing things up.
